language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://test.pactflow.io
  # Encrypted PACT_BROKER_TOKEN
  - secure: "fsddVVcDdt2P6+A66nHR0rvHyqZhc4ZH99rfsm+G9gC0cRiafEsPp43O1Cvn01iLRcHp/W+jNVrFqf72pIMkBI0HYadtiwsbKeHdJgrJMLEbnTy4ABJEVfN9DsO2K8/PLHkqmF+gpzF0wttOWm8t/J1wybPUZ1XOiptOcLyBZKq77mQHlorlDcd2DRoBGOb2bziDht4yin8/5zJV3V+pu9xvI+yjLNo3L36NTMwOqYkdaet6VpjI7Z3/iL7J/6++V9P1yoatZNBltMPZKyc/ww5vx5/JKXvgsXIiLZ27XKXswJLnk4usUpRf2ntmQDyIsbMv7ftqfGclyzvCG+jxYjEHHZ6dq9klgow/j6p4dVltXwqGzQrwWJtpDGhoTgj/fMqnQh431NuD6PhZs0S9c402el2P3DArIJLX5DNS9pwVaVP32PkMk7QqSvJar+xhtG+shfTHc/PWLbqGeaYwDJJSWLWCciMLEcO+YixeAKV10P+b7wqQlGDHJKafS+3tOQ9mZ+U5WqUGwHlxiOCJH3lizOkcan10AQ5n4ydPry8mrPHImtGB9rVIMCYOQVfhbqydgLDhd10vuZCnwUBMcRNEMu2fIdJUcT+oP8zJ0fq3+NWhLt0V8FexHIJPwPcezc7BnB1h8anZqD1KGwOGbLmTSn/vV1felQgXqjgAj+0="
before_script:
- docker pull pactfoundation/pact-cli:latest
script:
- make ci
