language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - REACT_APP_API_BASE_URL=http://localhost:8080
    - PACT_BROKER_BASE_URL=https://test.pactflow.io
    # Encrypted PACT_BROKER_TOKEN
    - secure: "Uotb50sbX8V3aaXN+JdN12N1FB0aPn/Nr5vtpYuHiGsP/fsiwhPXHARuO3q6YiunqWraLFwep2r1klC0YtahH5pG438RJrvpsXiHJCO9cIW2ggpekmo22LGMcbhwNwCJ+Afwob5OHGye02BCiCRLEEjzZ9eB3QC20hElakkId+MDN67hPRfS1I9GHniIUFErO1/yXLUAzmPwCSLf1oWqqUtF/NQyJMv5/os7FPKrS74t6sYIdaznckKu2O2Aw2qnJ3A7pxNP8RhtLDEMqUgjyqDsjWDygPfl5ZngofCrWhwkXSBOEVTRDNgbmLqtXsdTSkD70fP8xk2NsPUbNJU9SXQHtipWDIOoYmCCkcDsVJmutTNVeo30R0Syz0R/VbBZVdLnzK5N7xhE3XAbCVODZ3SPfkrWU72qda4Xu+KAuw3hftqniCWzJyxqaP/tXWspxJXYbPWGgH9M5tgiy0n0UZQO7UpirkiWoy7jdsqWFsLzynx5ARyOZOHh43qUBtFpHwthM4ASfIBZ9bkPyBeTWJSnTCpkjctNuaxGV1blY0Vo3v2pGtFlalFGuCR1Jkowc0jmFvmIgBVN8qckaaCr2BAeRfqPygsIcpcJ/wfi77JXz2PUUCMRU0Udt5Ahxrf6nG4b3zw2t/8T/VDYVueV6OcZ6CTz2zy32dESQe6N4Yc="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  - make ci
